# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel


class Authority:
    success: LangItem = LangItem("authority", "success")
    low_authority: LangItem = LangItem("authority", "low_authority")


class Bind:
    generated_1: LangItem = LangItem("bind", "generated_1")
    generated_2: LangItem = LangItem("bind", "generated_2")
    expire: LangItem = LangItem("bind", "expire")
    same_account: LangItem = LangItem("bind", "same_account")
    success: LangItem = LangItem("bind", "success")
    remove_success: LangItem = LangItem("bind", "remove_success")
    remove_original: LangItem = LangItem("bind", "remove_original")
    list: LangItem = LangItem("bind", "list")
    no_accounts: LangItem = LangItem("bind", "no_accounts")


class UserRename:
    duplicate: LangItem = LangItem("user", "rename.duplicate")
    updated: LangItem = LangItem("user", "rename.updated")


class User:
    message: LangItem = LangItem("user", "message")
    rename = UserRename


class Lang(LangModel):
    authority = Authority
    bind = Bind
    user = User
